apiVersion: apps/v1
kind: Deployment
metadata: 
  name: blue-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      deploy: blue
  template: 
    metadata:
      name: blue-pod
      labels:
        deploy: blue
    spec:
      containers:
        - name: blue-container
          image: oriyossef/blue
          ports:
            - containerPort: 5005