apiVersion: apps/v1
kind: Deployment
metadata: 
  name: flask-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      deploy: blue
  template: 
    metadata:
      name: flask-pod
      labels:
        deploy: flask
    spec:
      containers:
        - name: flask-container
          image: oriyossef/flaskapp
          ports:
            - containerPort: 5005